export default [
  { name: 'button', title: 'Button<br>&nbsp;',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Label Text',
        path:'label.text'
      },
      {
        label:'Background',
        path:'lookAndFeel.background',
        type:'color',
        defaultValue:'#2b91e6'
      },
      {
        label:'Foreground',
        path:'lookAndFeel.foreground',
        type:'color',
        defaultValue:'#ffffff'
      },
      {
        label:'Is Refresh',
        path:'isRefresh',
        type:'boolean'
      },
      {
        label:'Is Reload',
        path:'isReload',
        type:'boolean'
      },
      {
        label:'Is Reset',
        path:'isReset',
        type:'boolean'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
      
    ]
  },
  { name: 'reloadButton', title: 'Reload<br>Button', options:[
      {
        label:'Name',
        path:'name'
      },
  ] },
  { name: 'checkbox', title: 'Check<br>Box',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Checked',
        path:'isChecked',
        type:'boolean'
      },
      {
        label:'Label Text',
        path:'label.text'
      },
      {
        label:'Icon Color',
        path:'lookAndFeel.background',
        type:'color',
        defaultValue:'#2b91e6'
      },
      {
        label:'Foreground',
        path:'lookAndFeel.foreground',
        type:'color',
        defaultValue:'#ffffff'
      },
      {
        label:'Persistent',
        path:'persistent',
        type:'boolean'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'switch', title: 'Switch<br>&nbsp;',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Checked',
        path:'isChecked',
        type:'boolean'
      },
      {
        label:'Label Text',
        path:'label.text'
      },
      {
        label:'Icon Color',
        path:'lookAndFeel.background',
        type:'color',
        defaultValue:'#2b91e6'
      },
      {
        label:'Foreground',
        path:'lookAndFeel.foreground',
        type:'color',
        defaultValue:'#ffffff'
      },
      {
        label:'Persistent',
        path:'persistent',
        type:'boolean'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'radiobutton', title: 'Radio<br>&nbsp;',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Radio Group',
        path:'group'
      },
      {
        label:'Checked',
        path:'isChecked',
        type:'boolean'
      },
      {
        label:'Label Text',
        path:'label.text'
      },
      {
        label:'Icon Color',
        path:'lookAndFeel.background',
        type:'color',
        defaultValue:'#2b91e6'
      },
      {
        label:'Foreground',
        path:'lookAndFeel.foreground',
        type:'color',
        defaultValue:'#ffffff'
      },
      {
        label:'Persistent',
        path:'persistent',
        type:'boolean'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'combobox', title: 'Combo<br>Box',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Background',
        path:'lookAndFeel.background',
        type:'color',
        defaultValue:'#2b91e6'
      },
      {
        label:'Foreground',
        path:'lookAndFeel.foreground',
        type:'color',
        defaultValue:'#ffffff'
      },
      {
        label:'Persistent',
        path:'persistent',
        type:'boolean'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'choices', title: 'Choices<br>&nbsp;',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Background',
        path:'lookAndFeel.background',
        type:'color',
        defaultValue:'#2b91e6'
      },
      {
        label:'Foreground',
        path:'lookAndFeel.foreground',
        type:'color',
        defaultValue:'#ffffff'
      },
      {
        label:'Border Color',
        path:'style.normal.borderColor',
        type:'color',
        defaultValue:'#666'
      },
      {
        label:'Persistent',
        path:'persistent',
        type:'boolean'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'textInput', title: 'Text<br>&nbsp;',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Text',
        path:'value.defaultValue',
        defaultValue:''
      },
      {
        label:'Background',
        path:'lookAndFeel.background',
        type:'color',
        defaultValue:'#2b91e6'
      },
      {
        label:'Foreground',
        path:'lookAndFeel.foreground',
        type:'color',
        defaultValue:'#ffffff'
      },
      {
        label:'Persistent',
        path:'persistent',
        type:'boolean'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'range', title: 'Range<br>Slider',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Value',
        path:'value.defaultValue',
        defaultValue:50
      },
      {
        label:'Background',
        path:'lookAndFeel.background',
        type:'color',
        defaultValue:'#2b91e6'
      },
      {
        label:'Foreground',
        path:'lookAndFeel.foreground',
        type:'color',
        defaultValue:'#ffffff'
      },
      {
        label:'Persistent',
        path:'persistent',
        type:'boolean'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'progress', title: 'Progress<br>Bar',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Value',
        path:'value.defaultValue',
        defaultValue:50
      },
      {
        label:'Background',
        path:'lookAndFeel.background',
        type:'color',
        defaultValue:'#2b91e6'
      },
      {
        label:'Foreground',
        path:'lookAndFeel.foreground',
        type:'color',
        defaultValue:'#ffffff'
      },
      {
        label:'Persistent',
        path:'persistent',
        type:'boolean'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'colorPicker', title: 'Color<br>Picker',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Value',
        path:'value.defaultValue',
        type:'color',
        defaultValue:'#000000'
      },      
      {
        label:'Persistent',
        path:'persistent',
        type:'boolean'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'label', title: 'Label<br>&nbsp;',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Text',
        path:'text'
      },
      {
        label:'Background',
        path:'style.normal.backgroundColor',
        type:'color',
        defaultValue:'#00000000'
      },
      {
        label:'Foreground',
        path:'style.normal.color',
        type:'color',
        defaultValue:'#ffffff'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'icon', title: 'Icon<br>&nbsp;',
    options:[
      {
        label:'Name',
        path:'name'
      },      
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'frame', title: 'Frame<br>&nbsp;',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Title',
        path:'title.text'
      },      
      {
        label:'Foreground',
        path:'lookAndFeel.foreground',
        type:'color',
        defaultValue:'#ffffff'
      },      
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'grid', title: 'Grid<br>&nbsp;',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Background',
        path:'style.normal.backgroundColor',
        type:'color',
        defaultValue:'#00000000'
      },
      {
        label:'Border Color',
        path:'style.normal.borderColor',
        type:'color',
        defaultValue:'#666'
      },
      {
        label:'Persistent',
        path:'persistent',
        type:'boolean'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  {
    name: 'layoutContainer', title: 'Layout<br>Container',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Background',
        path:'style.normal.backgroundColor',
        type:'color',
        defaultValue:'#00000000'
      },
      {
        label:'Border Color',
        path:'style.normal.borderColor',
        type:'color',
        defaultValue:'#666'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ]
  },
  {
    name: 'splitPane', title: 'Split Pane',
    options:[
      {
        label:'Name',
        path:'name'
      },      
      {
        label:'Splitter Position',
        path:'spliiter.value',
        defaultValue:100
      },
      {
        label:'Splitter Thickness',
        path:'thickness',
        defaultValue:8
      },
      {
        label:'Background',
        path:'style.normal.backgroundColor',
        type:'color',
        defaultValue:'#00000000'
      },
      {
        label:'Border Color',
        path:'style.normal.borderColor',
        type:'color',
        defaultValue:'#666'
      },

      {
        label:'Pane 1 Background',
        path:'pane1.style.normal.backgroundColor',
        type:'color',
        defaultValue:'#00000000'
      },
      {
        label:'Pane 1 Border Color',
        path:'pane1.style.normal.borderColor',
        type:'color',
        defaultValue:'#666'
      },

      {
        label:'Pane 2 Background',
        path:'pane2.style.normal.backgroundColor',
        type:'color',
        defaultValue:'#00000000'
      },
      {
        label:'Pane 2 Border Color',
        path:'pane2.style.normal.borderColor',
        type:'color',
        defaultValue:'#666'
      },
      {
        label:'Persistent',
        path:'persistent',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ]
  },
  {
    name: 'panel', title: 'HTML<br>Panel',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'HTML',
        path:'HTML',
        defaultValue:'<marquee>HELLO MODERN WORLD WHERE ARE YOU GOING</marquee>'
      },
      {
        label:'Foreground',
        path:'style.normal.color',
        type:'color',
        defaultValue:'#CCCCCC'
      },    
      {
        label:'Background',
        path:'style.normal.backgroundColor',
        type:'color',
        defaultValue:'##333333'
      },
      {
        label:'Border Color',
        path:'style.normal.borderColor',
        type:'color',
        defaultValue:'#666'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'callout', title: 'Callout<br>&nbsp;',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Text',
        path:'panel.HTML'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ] },
  { name: 'overlay', title: 'Popup<br>Overlay',
    options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Background',
        path:'style.normal.backgroundColor',
        type:'color',
        defaultValue:'#00000066'
      },
      {
        label:'Border Color',
        path:'style.normal.borderColor',
        type:'color',
        defaultValue:'#FFFFFF33'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ]
  },
  {
    name:'dropBox', title:'DropBox<br>&nbsp;', options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'DropBox Name',
        path:'dropBoxName'
      },
      {
        label:'Background',
        path:'style.normal.backgroundColor',
        type:'color',
        defaultValue:'#00000000'
      },
      {
        label:'Border Color',
        path:'style.normal.borderColor',
        type:'color',
        defaultValue:'#666'
      },
      {
        label:'Persistent',
        path:'persistent',
        type:'boolean'
      },
      {
        label:'Disabled',
        path:'disabled',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ]
  },
  {
    name:'audio', title:'Audio<br>&nbsp;Player', options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Url to play',
        path:'url'
      },      
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ]
  },
  {
    name:'video', title:'Video<br>&nbsp;Player', options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Url to play',
        path:'url'
      },
      {
        label:'Autoplay',
        path:'autoplay',
        type:'boolean'
      },
      {
        label:'Loop',
        path:'loop',
        type:'boolean'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ]
  },
  {
    name:'audioRecorder', title:'Audio<br>Recorder', options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ]
  },
  {
    name:'transcriber', title:'Audio<br>Transcriber', options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ]
  },
  {
    name:'recorder', title:'Video<br>Recorder', options:[
      {
        label:'Name',
        path:'name'
      },
      {
        label:'Audio',
        path:'audio.enabled',
        type:'boolean',
        defaultValue:true
      },
      {
        label:'Video',
        path:'video.enabled',
        type:'boolean',
        defaultValue:true
      },
      {
        label:'Z-Index',
        path:'style.normal.zIndex',
        defaultValue:1
      },
    ]
  },
];